version: 2
updates:
  - package-ecosystem: "npm"
    directory: "./server"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "./client"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "daily"
