version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-type: "all"
        update-types: ["version-update:semver-major"]
    groups:
        all-dependencies:
          patterns:
            - "*"
