name: Prettier

on:
  pull_request:
    branches:
      - master

jobs:
  lint-and-prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run format

      - name: Debug Git State
        run: |
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Current changes:"
          git status
          git diff

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A  # Explicitly stage all changes
          git diff --quiet || git commit -m "chore: apply lint fixes and prettier formatting"
          git push --force origin "${{ github.head_ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
